### PR TITLE
#55, #154, #116 - Prompt for layer package or select alternate EGDB/GDB on start

### PR DESCRIPTION
**Pull request by csmoore**
Addresses: 

#55 - User should be able to select database containing Military Overlay feature classes  
#154 - User should be prompted about which schema they intend to add to their project at the outset, not when selecting the first symbol they want to use
#116 - Refactor code to have a single list of feature classes 

For #55, and #154 - there are prompts added when the Military Overlay Addin Dockpane is first used to prompt:

On Start:

1. No datamodel found in project, prompt to add:

form-adddatamodel

2. If "No" - prompt for database:

form-selectdatabase

3. If "Yes" bring up settings form that allows the database to be selected:

form-setdatabase

### CODE REVIEW

**Comment by csmoore** [comment]
Added the dialog/workflow changes and tested with different scenarios:

1. Project already have database with schema / does not have schema
2. FGDB + EGDB
3. Selected Database already has schema / schema not present
4. User cancels any of the add-schema steps, can still enable from settings

So hopefully this is ready to retest:

form-addlayernew

form-addlayernewsettings

**Comment by lfunkhouser** [comment]
@dfoll @topowright please merge after testing this workflow.

**Comment by csmoore** [comment]
These issues should now be addressed and ready for retest. Also, in order to make this change, the addin is now completely disabled (search and favorites tabs also) until the database and standard is selected. 

Looks like this (grayed out) until enabled with database/standard now:

image

**Comment by topowright** [comment]
@csmoore with the changes currently made if a user cancels before creating the data model the add-in does not enable the search window and there is no way to then add the data model to the current project.  We need to enable the search capability to allow the user to have the same experince that they have had with previous releases. I understand that they can go to the settings text button and add a schema, but they need to be able to add it on search as well.

**Comment by csmoore** [comment]
@topowright - With the other requested change (to bring up the settings window before selecting a standard or adding the datamodel) I did need to make that change to completely disable the addin until the user chooses the standard. Otherwise the addin does not know which style/standard to look for symbols in.

If the settings are canceled, the user can still enable the addin from the settings button, not sure if that should be documented.

**Comment by topowright** [comment]
If that is the case then we should implement a feature that when the user clicks the search area they are prompted to choose a standard. Currently there is no clear path for the user on how to enable the add-in. @dfoll @lfunkhouser please weight in.

**Pull request merged**
